# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "80:80"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d     
    ports:
      - 5432:5432       
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080